//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarteiraVirtualWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int idCliente { get; set; }
        public string nomeCliente { get; set; }
        public string sobreCliente { get; set; }
        public string emailCliente { get; set; }
        public string cepCliente { get; set; }
        public string cpfCliente { get; set; }
        public string rgCliente { get; set; }
        public Nullable<System.DateTime> dtNasc { get; set; }
        public string sexo { get; set; }
        public Nullable<int> telCliente { get; set; }
        public Nullable<int> celCliente { get; set; }
        public Nullable<System.DateTime> dtRegistro { get; set; }
        public string senha { get; set; }
        public string data { get; set; }
    }
}
