//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarteiraVirtualWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parceiro
    {
        public int idParceiro { get; set; }
        public string CNPJ { get; set; }
        public string emailParceiro { get; set; }
        public string razaoParceiro { get; set; }
        public string cpfParceiro { get; set; }
    }
}
