//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarteiraVirtualWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Senha
    {
        public int idSenha { get; set; }
        public Nullable<int> fkCarteira { get; set; }
        public string canal { get; set; }
        public string senha1 { get; set; }
        public Nullable<byte> senhaopcional { get; set; }
    }
}
